### PR TITLE
editing SVM analysis example 

### PR DESCRIPTION
**Pull request by be-apt**
using JuMP instead of MOI (less code, more understandable)
fixed a minor typo

### CODE REVIEW

**Comment by be-apt** [comment]
@joaquimg any clue why is this failing? the script `unit_example.jl` was working earlier i guess

**Comment by matbesancon** [comment]
just re-running to see if the error on nightly is still there

**Comment by matbesancon** [comment]
@be-apt when using `julia` in quote blocks in documentation, it will just create a colorized snippet. What we want is actually running the code, that's why the blocks are named

**Comment by be-apt** [comment]
i guess we can drop `example 1` vs `julia` thing once https://github.com/jump-dev/DiffOpt.jl/issues/93 is closed

**Comment by matbesancon** [comment]
@be-apt for now let's keep the `example 1` blocks to have the examples built, we can move to Literate later

**Comment by matbesancon** [comment]
example failing here

**Comment by be-apt** [comment]
closing this. just a duplicate of #95

**Pull request closed without merging**
