### PR TITLE
BackwardOut -> BackwardOutConstraint

### PR DESCRIPTION
**Pull request by blegat**
By converting the test "Differentiating MOI examples 1" to `qp_test`, the test was failing and I was able to fix it by doing the changes suggested in https://github.com/jump-dev/DiffOpt.jl/issues/124 and https://github.com/jump-dev/DiffOpt.jl/issues/127.
So I'm quite confident on the changes on these lines.

Closes https://github.com/jump-dev/DiffOpt.jl/issues/124
Closes https://github.com/jump-dev/DiffOpt.jl/issues/127

### CODE REVIEW

**Comment by matbesancon** [comment]
Current error seems to be some size not implemented for `LazyArrays.Applied`

```julia
Differentiating simple PSD back: Error During Test at /home/runner/work/DiffOpt.jl/DiffOpt.jl/test/conic_backward.jl:10
  Got exception outside of a @test
  MethodError: no method matching size(::LazyArrays.Applied{LazyArrays.DefaultArrayApplyStyle, typeof(DiffOpt._view), Tuple{Vector{Float64}, UnitRange{Int64}}})
  Closest candidates are:
    size(::Union{QR, LinearAlgebra.QRCompactWY, QRPivoted}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/qr.jl:524
    size(::Union{QR, LinearAlgebra.QRCompactWY, QRPivoted}, ::Integer) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/qr.jl:523
    size(::Union{Cholesky, CholeskyPivoted}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/cholesky.jl:442
    ...
  Stacktrace:
    [1] axes
      @ ./abstractarray.jl:89 [inlined]
    [2] combine_axes
      @ ./broadcast.jl:484 [inlined]
    [3] instantiate
      @ ./broadcast.jl:266 [inlined]
    [4] _get_dA(b_cache::DiffOpt.ConicBackCache, g_cache::DiffOpt.ConicCache, ci::MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Zeros})
      @ DiffOpt ~/work/DiffOpt.jl/DiffOpt.jl/src/diff_opt.jl:454
```

**Comment by blegat** [comment]
The failing on Julia CI nightly seems to be a nightly bug

**Comment by matbesancon** [comment]
This looks good to merge, should we mention somewhere how/why we are using lazy function application to arrays?

**Review by matbesancon — APPROVED** [review]

**Comment by blegat** [comment]
Yes, we should definitely, I'm going to add something in the paper at least but we should also add it to the doc

**Pull request merged**
