### PR TITLE
Renaming

### LINKED ISSUE #208: Rename Backward to Reverse
What's the correct terminology ? The classical terminology is forward mode AD vs reverse mode AD, as in, `frule` and `rrule` so we should have `Reverse...` attributes and `DiffOpt.reverse` instead of `Backward...` and `DiffOpt.backward`.

### PR DESCRIPTION
**Pull request by matbesancon**
Closes #208

### CODE REVIEW

**Comment by matbesancon** [comment]
ping @blegat @joaquimg
We can bikeshed the names, it's just a global search-and-replace now
I added the former attributes in `src/deprecated.jl`

**Comment by blegat** [comment]
See my comment in https://github.com/jump-dev/DiffOpt.jl/issues/208#issuecomment-1102589302

**Comment by matbesancon** [comment]
done in last commit

**Comment by matbesancon** [comment]
All done @blegat

**Pull request merged**
